<?php
return array (
  'nav._default' => 'Default (no selected tab)',
  'nav.contributedThreads' => 'Threads with your posts',
  'nav.currentVisitors' => 'Current visitors',
  'nav.defaultLatestActivity' => 'Latest activity',
  'nav.defaultLogOut' => 'Log out',
  'nav.defaultNewsFeed' => 'Your news feed',
  'nav.defaultRegister' => 'Register',
  'nav.defaultYourAccount' => 'Your account',
  'nav.defaultYourProfile' => 'Your profile',
  'nav.findThreads' => 'Find threads',
  'nav.forumList' => 'Forum list',
  'nav.forums' => '<i class="far fa-comments"></i> Forums',
  'nav.home' => 'Home',
  'nav.latestActivity' => 'Latest activity',
  'nav.markForumsRead' => 'Mark forums read',
  'nav.members' => '<i class="fal fa-users"></i> Members',
  'nav.newPosts' => 'New posts',
  'nav.newProfilePosts' => 'New profile posts',
  'nav.registeredMembers' => 'Registered members',
  'nav.searchForums' => 'Search forums',
  'nav.searchProfilePosts' => 'Search profile posts',
  'nav.unansweredThreads' => 'Unanswered threads',
  'nav.watched' => 'Watched',
  'nav.watchedForums' => 'Watched forums',
  'nav.watchedThreads' => 'Watched threads',
  'nav.whatsNew' => '<i class="far fa-newspaper"></i> What\'s new',
  'nav.whatsNewNewsFeed' => 'Your news feed',
  'nav.whatsNewPosts' => 'New posts',
  'nav.whatsNewProfilePosts' => 'New profile posts',
  'nav.yourThreads' => 'Your threads',
);